spring:
  cloud:
    gateway:
      # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        # 路由器ID，没有固定规则但要求唯一，建议配合服务名
        - id: consumer-member
          # 匹配后提供服务的路由地址
          # uri: http://localhost:8001
          uri: lb://consumer-member
          # 断言，路径相匹配的进行路由
          predicates:
            - Path=/consumer/member/**

        - id: provider-message
          # uri: http://localhost:7001
          uri: lb://provider-message
          predicates:
            - Path=/message/mail/**